/*******************************************************************************
 * Copyright (c) 2024 DFKI.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     DFKI - Tapanta Bhanja <tapanta.bhanja@dfki.de>
 *******************************************************************************/ 
package caraas.module.submodels.act_of_observation;

import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.List;

import java.math.BigInteger; 

import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.datatype.Duration;
import javax.xml.namespace.QName;

import caraas.connection.ConnectedDevices;
//import caraas.connection.DataCrawler;
import caraas.module.AASServer;
import caraas.module.ConceptDescriptions;
import caraas.connection.OpcUaVariable;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.operation.Operation;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.SubmodelElementCollection;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.dataelement.property.valuetype.ValueType;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.dataelement.File;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.dataelement.property.Property;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.dataelement.MultiLanguageProperty;
import org.eclipse.basyx.submodel.metamodel.map.qualifier.LangStrings;
import org.eclipse.basyx.submodel.metamodel.map.reference.Key; 
import org.eclipse.basyx.submodel.metamodel.map.reference.Reference; 
import org.eclipse.basyx.submodel.metamodel.api.reference.IKey;
import org.eclipse.basyx.submodel.metamodel.api.reference.enums.KeyElements; 
import org.eclipse.basyx.submodel.metamodel.api.reference.enums.KeyType; 
import org.eclipse.basyx.submodel.metamodel.api.identifier.IdentifierType;
import org.eclipse.basyx.submodel.metamodel.api.qualifier.haskind.ModelingKind;
import org.eclipse.basyx.submodel.metamodel.api.submodelelement.ISubmodelElement;
import org.eclipse.basyx.submodel.metamodel.map.Submodel;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.operation.OperationVariable;
import com.festo.aas.p4m.connection.ValueDelegate; 
import org.eclipse.basyx.vab.protocol.opcua.types.NodeId;
import org.eclipse.basyx.vab.protocol.opcua.types.UnsignedShort;
import com.festo.aas.p4m.connection.ConnectedProperty;

/**
 * 
 * @author DFKI
 * 
 * Do not edit this file for changing operation behaviours. 
 */

public class Act_Of_Observation extends Submodel {

	/**
	 * This field variable holds all configured connectors to the asset. 
	 * Use these connectors to communicate with your asset.
	 */
	private ConnectedDevices connectedDevices;

	private ConceptDescriptions conceptDescriptions;

	/**
     * This class contains all user-provided code for operations.
     */
	private final DynamicElementsWorkspace dew; 

	 /**
     * This class contains all user-provided code for value delegates.
     */

	 /**
     * The following contains the declaration of the operation variables as field variables so that they can be accessed in their true sense.
     */


	public Act_Of_Observation() {

		try {
			connectedDevices = new ConnectedDevices();
		} 
		catch (Exception e) {

			e.printStackTrace();
		}
		
		dew = new DynamicElementsWorkspace(connectedDevices);
		conceptDescriptions = new ConceptDescriptions();

		setIdShort("Act_Of_Observation");
		setIdentification(IdentifierType.IRI, AASServer.getSettings().SUBMODEL_ACT_OF_OBSERVATION_IRI.get().toString()); 
		setKind(ModelingKind.TEMPLATE); 
		List<IKey> act_of_observationKeys= new ArrayList<IKey>();
		Reference Act_Of_ObservationRef = new Reference(act_of_observationKeys);
		setSemanticId(Act_Of_ObservationRef); 
 
		Property Act_Of_Observation_occursAt= new Property();
		Act_Of_Observation_occursAt.setIdShort("occursAt");
		Act_Of_Observation_occursAt.setValueType(ValueType.DateTime);
		List<IKey> Act_Of_Observation_occursatKeys= new ArrayList<IKey>();
		Reference Act_Of_Observation_occursAtRef = new Reference(Act_Of_Observation_occursatKeys);
		Act_Of_Observation_occursAt.setSemanticId(Act_Of_Observation_occursAtRef); 
 
		Act_Of_Observation_occursAt.setKind(ModelingKind.TEMPLATE);
		addSubmodelElement(Act_Of_Observation_occursAt);
		Act_Of_Observation_occursAt.setValue("null");


		SubmodelElementCollection Act_Of_Observation_Image_Taking_Mesuring_Process = new SubmodelElementCollection();
		Collection<ISubmodelElement> Act_Of_Observation_Image_Taking_Mesuring_Processvalue = new ArrayList<ISubmodelElement>();
		Act_Of_Observation_Image_Taking_Mesuring_Process.setIdShort("Image_Taking_Mesuring_Process");
		Act_Of_Observation_Image_Taking_Mesuring_Process.setAllowDuplicates(false);
		Act_Of_Observation_Image_Taking_Mesuring_Process.setOrdered(false);
     	Act_Of_Observation_Image_Taking_Mesuring_Process.setKind(ModelingKind.TEMPLATE);
		addSubmodelElement(Act_Of_Observation_Image_Taking_Mesuring_Process);
		List<IKey> Act_Of_Observation_image_taking_mesuring_processKeys= new ArrayList<IKey>();
		Reference Act_Of_Observation_Image_Taking_Mesuring_ProcessRef = new Reference(Act_Of_Observation_image_taking_mesuring_processKeys);
		Act_Of_Observation_Image_Taking_Mesuring_Process.setSemanticId(Act_Of_Observation_Image_Taking_Mesuring_ProcessRef); 
 


		// Adding the SubmodelElements that belong to SubmodelElementCollection - Image_Taking_Mesuring_Process. 
		Act_Of_Observation_Image_Taking_Mesuring_Process.setElements(Act_Of_Observation_Image_Taking_Mesuring_Processvalue.stream().collect(Collectors.toMap(ISubmodelElement::getIdShort, Function.identity())));
 
		SubmodelElementCollection Act_Of_Observation_Battery_Level_Mesuring_Process = new SubmodelElementCollection();
		Collection<ISubmodelElement> Act_Of_Observation_Battery_Level_Mesuring_Processvalue = new ArrayList<ISubmodelElement>();
		Act_Of_Observation_Battery_Level_Mesuring_Process.setIdShort("Battery_Level_Mesuring_Process");
		Act_Of_Observation_Battery_Level_Mesuring_Process.setAllowDuplicates(false);
		Act_Of_Observation_Battery_Level_Mesuring_Process.setOrdered(false);
     	Act_Of_Observation_Battery_Level_Mesuring_Process.setKind(ModelingKind.TEMPLATE);
		addSubmodelElement(Act_Of_Observation_Battery_Level_Mesuring_Process);
		List<IKey> Act_Of_Observation_battery_level_mesuring_processKeys= new ArrayList<IKey>();
		Reference Act_Of_Observation_Battery_Level_Mesuring_ProcessRef = new Reference(Act_Of_Observation_battery_level_mesuring_processKeys);
		Act_Of_Observation_Battery_Level_Mesuring_Process.setSemanticId(Act_Of_Observation_Battery_Level_Mesuring_ProcessRef); 
 


		// Adding the SubmodelElements that belong to SubmodelElementCollection - Battery_Level_Mesuring_Process. 
		Act_Of_Observation_Battery_Level_Mesuring_Process.setElements(Act_Of_Observation_Battery_Level_Mesuring_Processvalue.stream().collect(Collectors.toMap(ISubmodelElement::getIdShort, Function.identity())));
 
		SubmodelElementCollection Act_Of_Observation_Engine_Speed_Mesuring_Process = new SubmodelElementCollection();
		Collection<ISubmodelElement> Act_Of_Observation_Engine_Speed_Mesuring_Processvalue = new ArrayList<ISubmodelElement>();
		Act_Of_Observation_Engine_Speed_Mesuring_Process.setIdShort("Engine_Speed_Mesuring_Process");
		Act_Of_Observation_Engine_Speed_Mesuring_Process.setAllowDuplicates(false);
		Act_Of_Observation_Engine_Speed_Mesuring_Process.setOrdered(false);
     	Act_Of_Observation_Engine_Speed_Mesuring_Process.setKind(ModelingKind.TEMPLATE);
		addSubmodelElement(Act_Of_Observation_Engine_Speed_Mesuring_Process);
		List<IKey> Act_Of_Observation_engine_speed_mesuring_processKeys= new ArrayList<IKey>();
		Reference Act_Of_Observation_Engine_Speed_Mesuring_ProcessRef = new Reference(Act_Of_Observation_engine_speed_mesuring_processKeys);
		Act_Of_Observation_Engine_Speed_Mesuring_Process.setSemanticId(Act_Of_Observation_Engine_Speed_Mesuring_ProcessRef); 
 


		// Adding the SubmodelElements that belong to SubmodelElementCollection - Engine_Speed_Mesuring_Process. 
		Act_Of_Observation_Engine_Speed_Mesuring_Process.setElements(Act_Of_Observation_Engine_Speed_Mesuring_Processvalue.stream().collect(Collectors.toMap(ISubmodelElement::getIdShort, Function.identity())));
 
		SubmodelElementCollection Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process = new SubmodelElementCollection();
		Collection<ISubmodelElement> Act_Of_Observation_Ultrasonic_Distance_Mesuring_Processvalue = new ArrayList<ISubmodelElement>();
		Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process.setIdShort("Ultrasonic_Distance_Mesuring_Process");
		Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process.setAllowDuplicates(false);
		Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process.setOrdered(false);
     	Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process.setKind(ModelingKind.TEMPLATE);
		addSubmodelElement(Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process);
		List<IKey> Act_Of_Observation_ultrasonic_distance_mesuring_processKeys= new ArrayList<IKey>();
		Reference Act_Of_Observation_Ultrasonic_Distance_Mesuring_ProcessRef = new Reference(Act_Of_Observation_ultrasonic_distance_mesuring_processKeys);
		Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process.setSemanticId(Act_Of_Observation_Ultrasonic_Distance_Mesuring_ProcessRef); 
 


		// Adding the SubmodelElements that belong to SubmodelElementCollection - Ultrasonic_Distance_Mesuring_Process. 
		Act_Of_Observation_Ultrasonic_Distance_Mesuring_Process.setElements(Act_Of_Observation_Ultrasonic_Distance_Mesuring_Processvalue.stream().collect(Collectors.toMap(ISubmodelElement::getIdShort, Function.identity())));
 
	}
	
}

